version: '3.8'

services:
  broker:
    image: rabbitmq:3.13
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_MESSAGE_TTL: 120000 # 2 minutes
